[package]
name = "core"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "commune"
path = "src/lib.rs"

[dependencies]
handlebars = "5.0.0"
lettre = "0.11"
rand = "0.8.5"
redis = { version = "0.24.0", features = ["aio", "tokio-comp"] }
thiserror = "1.0.50"
tokio-postgres = { version = "0.7.10", features = ["with-serde_json-1"] }
validator = { version = "0.16", features = ["derive"] }

# Workspace
http = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features= ["serde"] }
url = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["full"] }

# Local Dependencies
matrix = { path = "../matrix" }
